apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chat.fullname" . }}-db
  labels:
    {{- include "chat.labels" . | nindent 4 }}
type: Opaque
stringData:
  connectionString: "Host={{ .Values.postgresql.host }};Port={{ .Values.postgresql.port }};Database={{ .Values.postgresql.database }};Username={{ .Values.postgresql.username }};Password={{ .Values.postgresql.password }}"
